Oppdatere pakker med kjente feil
FHIDev/fhi.helseid pull request #440
Opened 2024-09-18 11:53 UTC by yne-bv

Altinn-prosjektet har nå versjon 6 og 8 for .net
❓ Usikker på hva jeg skal sette versjonen som, og om det har noe å si

Pakker som har blitt lagt til
- System.Text.Json - 8.0.4
   - Refit har en avhengighet til 8.0.1
- IdentityModel.AspNetCore - 4.0.1
  - IdentityServer4.AccessTokenValidation har en avhengighet til 4.0.0
- System.Security.Cryptography.Pkcs - 6.0.4
   -  System.ServiceModel.Primitives har en avhengighet til System.Security.Cryptography.Xml - 6.2.0
      - Denne er avhengig av System.Security.Cryptography.Pkcs 6.0.1
- System.Formats.Asn1 - 6.0.1 
  - System.Security.Cryptography.Pkcs er avhengig av System.Formats.Asn1 - 6.0.0
- System.Text.Encodings.Web
  - AspNetCore.DataProtection.SqlServer er avhengig av Microsoft.AspNetCore.DataProtection som er avhengig av Microsoft.AspNetCore.Hosting.Abstractions som er avhengig av Microsoft.AspNetCore.Http.Abstractions som er avhengig av System.Text.Encodings.Web 4.4.0
  På denne var det ingen patch, man må gå opp en minor versjon
  
![image](https://github.com/user-attachments/assets/63d3a655-a9d9-438a-8f10-a61de3fe6bed)

2024-09-18 12:28 UTC, martinmine commented on Directory.Packages.props
> +    <PackageVersion Include="IdentityModel.AspNetCore" Version="4.0.1" />
Er det hensiktsmessig at vi går ned i versjon her? Burde vi gå opp istedenfor?

2024-09-18 12:29 UTC, martinmine commented
Ser Altinn-prosjektet har en del sårbarheter som det meldes om her. Ettersom det er en feature som aldri ble ferdig foreslår jeg at vi tar og legger det ut på en egen feature branch, og så sletter vi den dra repoet når det er noe vi ikke shipper med HelseID atm.

2024-09-18 12:32 UTC, yne-bv commented
> Ser Altinn-prosjektet har en del sårbarheter som det meldes om her. Ettersom det er en feature som aldri ble ferdig foreslår jeg at vi tar og legger det ut på en egen feature branch, og så sletter vi den dra repoet når det er noe vi ikke shipper med HelseID atm.

Støttes

2024-09-18 12:38 UTC, yne-bv commented on Directory.Packages.props
> +    <PackageVersion Include="IdentityModel.AspNetCore" Version="4.0.1" />
Jeg overså at Common prosjektet bruker denne pakken direkte, og ikke indirekte som Altinn gjør.
Jeg tok 4.0.1 fordi det er den nærmeste versjonen til 4.0.0 (som IdentityServer4.AccessTokenValidation bruker).
Men i og med at vi bruker 4.3.0 andre steder så tenker jeg vi bruker den nyeste.

2024-09-24 09:30 UTC, OsirisTerje requested changes

2024-09-24 09:30 UTC, OsirisTerje commented on .github/workflows/Fhi.HelseId.CI.yml
> -            6.0.x
Hvorfor fjerne denne ?

2024-09-24 13:34 UTC, OsirisTerje approved these changes

2024-09-25 05:50 UTC, merged